import type { SettingsSchema } from '@serverforge/core';

/**
 * Palworld settings.
 *
 * Everything below `Server` group lands inside the single `OptionSettings`
 * tuple in `PalWorldSettings.ini`. The adapter's `applySettings` reads the
 * existing tuple, overwrites only the keys we model, and writes it back —
 * so keys added by a future Palworld patch survive our round-trip.
 */
export function palworldSettingsSchema(variantId: string): SettingsSchema {
  const ini = (key: string) =>
    ({
      kind: 'ini' as const,
      file: 'Pal/Saved/Config/LinuxServer/PalWorldSettings.ini',
      section: '/Script/Pal.PalGameWorldSettings',
      key,
    });

  const schema: SettingsSchema = [
    // ── Server ──────────────────────────────────────────────────────────
    {
      key: 'ServerName',
      type: 'string',
      label: 'Server name',
      help: 'Shown in the in-game server browser.',
      tier: 'basic',
      group: 'Server',
      default: 'A ServerForge Palworld server',
      maxLength: 96,
      target: ini('ServerName'),
    },
    {
      key: 'ServerDescription',
      type: 'string',
      label: 'Description',
      help: 'A short line describing your server. Shown when players select it.',
      tier: 'basic',
      group: 'Server',
      default: '',
      maxLength: 256,
      multiline: true,
      target: ini('ServerDescription'),
    },
    {
      key: 'ServerPassword',
      type: 'string',
      label: 'Join password',
      help: 'Leave empty for an open server. Players are asked for this before joining.',
      tier: 'basic',
      group: 'Server',
      default: '',
      secret: true,
      maxLength: 64,
      target: ini('ServerPassword'),
    },
    {
      key: 'ServerPlayerMaxNum',
      type: 'number',
      label: 'Max players',
      help: 'Palworld is memory-hungry: budget about 1 GB per player on top of the base 8 GB.',
      tier: 'basic',
      group: 'Server',
      default: 16,
      min: 1,
      max: 32,
      unit: 'players',
      restartRequired: true,
      target: ini('ServerPlayerMaxNum'),
    },
    {
      key: 'AdminPassword',
      type: 'string',
      label: 'Admin password',
      help: 'Lets you run admin commands from inside the game. Keep it different from the join password.',
      tier: 'basic',
      group: 'Server',
      default: '',
      secret: true,
      maxLength: 64,
      target: ini('AdminPassword'),
    },
    {
      key: 'bIsMultiplay',
      type: 'boolean',
      label: 'Multiplayer',
      help: 'Leave on. Off turns the world into a single-player save.',
      tier: 'expert',
      group: 'Server',
      default: false,
      target: ini('bIsMultiplay'),
    },

    // ── Difficulty ──────────────────────────────────────────────────────
    {
      key: 'Difficulty',
      type: 'enum',
      label: 'Difficulty preset',
      help: 'Palworld applies its own curve on top of your individual rate settings. "None" means your rates are used exactly as set.',
      tier: 'basic',
      group: 'Difficulty',
      default: 'None',
      options: [
        { value: 'None', label: 'Custom (use my rates)' },
        { value: 'Casual', label: 'Casual' },
        { value: 'Normal', label: 'Normal' },
        { value: 'Hard', label: 'Hard' },
      ],
      target: ini('Difficulty'),
    },
    {
      key: 'DeathPenalty',
      type: 'enum',
      label: 'What players drop on death',
      help: 'The single most argued-about setting on any Palworld server.',
      tier: 'basic',
      group: 'Difficulty',
      default: 'All',
      options: [
        { value: 'None', label: 'Nothing' },
        { value: 'Item', label: 'Items only' },
        { value: 'ItemAndEquipment', label: 'Items and equipment' },
        { value: 'All', label: 'Everything, including Pals' },
      ],
      target: ini('DeathPenalty'),
    },
    {
      key: 'ExpRate',
      type: 'number',
      label: 'Experience rate',
      help: '1 is the normal game. 2 means players level twice as fast.',
      tier: 'basic',
      group: 'Difficulty',
      default: 1,
      min: 0.1,
      max: 20,
      step: 0.1,
      unit: '×',
      target: ini('ExpRate'),
    },
    {
      key: 'PalCaptureRate',
      type: 'number',
      label: 'Pal capture rate',
      help: 'Higher values make Pals easier to catch.',
      tier: 'advanced',
      group: 'Difficulty',
      default: 1,
      min: 0.5,
      max: 20,
      step: 0.1,
      unit: '×',
      target: ini('PalCaptureRate'),
    },
    {
      key: 'CollectionDropRate',
      type: 'number',
      label: 'Gathering rate',
      help: 'How much ore, wood and stone each hit yields.',
      tier: 'advanced',
      group: 'Difficulty',
      default: 1,
      min: 0.1,
      max: 20,
      step: 0.1,
      unit: '×',
      target: ini('CollectionDropRate'),
    },
    {
      key: 'EnemyDropItemRate',
      type: 'number',
      label: 'Enemy drop rate',
      help: 'How much loot defeated enemies leave behind.',
      tier: 'advanced',
      group: 'Difficulty',
      default: 1,
      min: 0.1,
      max: 20,
      step: 0.1,
      unit: '×',
      target: ini('EnemyDropItemRate'),
    },
    {
      key: 'DayTimeSpeedRate',
      type: 'number',
      label: 'Daytime speed',
      help: 'Higher values make days pass faster.',
      tier: 'advanced',
      group: 'Difficulty',
      default: 1,
      min: 0.1,
      max: 5,
      step: 0.1,
      unit: '×',
      target: ini('DayTimeSpeedRate'),
    },
    {
      key: 'NightTimeSpeedRate',
      type: 'number',
      label: 'Nighttime speed',
      help: 'Raise this to shorten nights, which players generally prefer.',
      tier: 'advanced',
      group: 'Difficulty',
      default: 1,
      min: 0.1,
      max: 5,
      step: 0.1,
      unit: '×',
      target: ini('NightTimeSpeedRate'),
    },

    // ── Building and PvP ────────────────────────────────────────────────
    {
      key: 'bEnablePlayerToPlayerDamage',
      type: 'boolean',
      label: 'Players can damage each other',
      help: 'Off makes the server fully cooperative.',
      tier: 'basic',
      group: 'Rules',
      default: false,
      target: ini('bEnablePlayerToPlayerDamage'),
    },
    {
      key: 'bEnableFriendlyFire',
      type: 'boolean',
      label: 'Friendly fire',
      help: 'Whether guild members can hurt each other.',
      tier: 'advanced',
      group: 'Rules',
      default: false,
      showWhen: { key: 'bEnablePlayerToPlayerDamage', equals: [true] },
      target: ini('bEnableFriendlyFire'),
    },
    {
      key: 'bEnableInvaderEnemy',
      type: 'boolean',
      label: 'Raids on player bases',
      help: 'Periodic attacks on bases. Turning this off is the usual fix for base-destruction complaints.',
      tier: 'advanced',
      group: 'Rules',
      default: true,
      target: ini('bEnableInvaderEnemy'),
    },
    {
      key: 'BuildObjectDamageRate',
      type: 'number',
      label: 'Structure damage rate',
      help: 'How much damage buildings take. 0 makes bases indestructible.',
      tier: 'advanced',
      group: 'Rules',
      default: 1,
      min: 0,
      max: 10,
      step: 0.1,
      unit: '×',
      target: ini('BuildObjectDamageRate'),
    },
    {
      key: 'GuildPlayerMaxNum',
      type: 'number',
      label: 'Max guild size',
      help: 'How many players can be in one guild.',
      tier: 'advanced',
      group: 'Rules',
      default: 20,
      min: 1,
      max: 100,
      unit: 'players',
      target: ini('GuildPlayerMaxNum'),
    },
    {
      key: 'BaseCampMaxNumInGuild',
      type: 'number',
      label: 'Bases per guild',
      help: 'Each active base costs server memory and CPU. Lower this if the server struggles.',
      tier: 'advanced',
      group: 'Rules',
      default: 4,
      min: 1,
      max: 10,
      unit: 'bases',
      target: ini('BaseCampMaxNumInGuild'),
    },

    // ── Performance ─────────────────────────────────────────────────────
    {
      key: 'bIsUseBackupSaveData',
      type: 'boolean',
      label: "Keep Palworld's own save backups",
      help: 'Independent of ServerForge backups. Costs disk but has saved many worlds.',
      tier: 'advanced',
      group: 'Performance',
      default: true,
      target: ini('bIsUseBackupSaveData'),
    },
    {
      key: 'AutoSaveSpan',
      type: 'number',
      label: 'Autosave interval',
      help: 'Seconds between world saves. Long intervals cause a visible stutter when the save finally happens.',
      tier: 'advanced',
      group: 'Performance',
      default: 180,
      min: 30,
      max: 3600,
      unit: 'seconds',
      target: ini('AutoSaveSpan'),
    },
    {
      key: 'sf_use_perf_threads',
      type: 'boolean',
      label: 'Performance threading flags',
      help: 'Adds the community-standard multithreading flags to the launch command. Recommended on any machine with 4 or more cores.',
      tier: 'advanced',
      group: 'Performance',
      default: true,
      restartRequired: true,
      target: { kind: 'internal' },
    },
    {
      key: 'RESTAPIEnabled',
      type: 'boolean',
      label: 'Enable the REST API',
      help: 'Lets tools query players and run admin commands over HTTP. The panel uses it for the live player list when it is on.',
      tier: 'advanced',
      group: 'Performance',
      default: true,
      restartRequired: true,
      target: ini('RESTAPIEnabled'),
    },
  ];

  if (variantId === 'palworld-modded') {
    schema.unshift({
      key: 'sf_enable_ue4ss',
      type: 'boolean',
      label: 'Install UE4SS mod loader',
      help: 'Most Palworld mods need this loader. We install it for you and place a mods folder in the file manager.',
      tier: 'basic',
      group: 'Mods',
      default: true,
      restartRequired: true,
      target: { kind: 'internal' },
    });
  }

  return schema;
}
