import type { SettingsSchema } from '@serverforge/core';

/**
 * Minecraft settings, written to `server.properties`.
 *
 * Help text rule for this file: assume the reader has never seen a config
 * file. No "see the wiki", no restating the key name as a sentence.
 */
export function minecraftSettingsSchema(variantId: string): SettingsSchema {
  const schema: SettingsSchema = [
    // ── Basics ──────────────────────────────────────────────────────────
    {
      key: 'motd',
      type: 'string',
      label: 'Server message',
      help: 'The line players see under your server name in their server list.',
      tier: 'basic',
      group: 'Basics',
      default: 'A ServerForge server',
      maxLength: 120,
      target: { kind: 'properties', file: 'server.properties', key: 'motd' },
    },
    {
      key: 'max-players',
      type: 'number',
      label: 'Max players',
      help: 'How many people can be online at once. Each player needs roughly 200–400 MB of memory on a modded server.',
      tier: 'basic',
      group: 'Basics',
      default: 10,
      min: 1,
      max: 1000,
      unit: 'players',
      target: { kind: 'properties', file: 'server.properties', key: 'max-players' },
    },
    {
      key: 'gamemode',
      type: 'enum',
      label: 'Game mode',
      help: 'What players start in. Survival is the normal Minecraft experience.',
      tier: 'basic',
      group: 'Basics',
      default: 'survival',
      options: [
        { value: 'survival', label: 'Survival', help: 'Gather resources, take damage, the normal game.' },
        { value: 'creative', label: 'Creative', help: 'Unlimited blocks, flight, no damage.' },
        { value: 'adventure', label: 'Adventure', help: 'Survival, but blocks can only be broken with the right tool. Used by map makers.' },
        { value: 'spectator', label: 'Spectator', help: 'Fly through the world without interacting.' },
      ],
      target: { kind: 'properties', file: 'server.properties', key: 'gamemode' },
    },
    {
      key: 'difficulty',
      type: 'enum',
      label: 'Difficulty',
      help: 'How dangerous monsters are. Peaceful removes them entirely.',
      tier: 'basic',
      group: 'Basics',
      default: 'normal',
      options: [
        { value: 'peaceful', label: 'Peaceful' },
        { value: 'easy', label: 'Easy' },
        { value: 'normal', label: 'Normal' },
        { value: 'hard', label: 'Hard' },
      ],
      target: { kind: 'properties', file: 'server.properties', key: 'difficulty' },
    },
    {
      key: 'online-mode',
      type: 'boolean',
      label: 'Require a Minecraft account',
      help: 'Verifies each player owns Minecraft. Turning this off lets anyone join using any username — only do that if the server is not reachable from the internet.',
      tier: 'basic',
      group: 'Basics',
      default: true,
      restartRequired: true,
      target: { kind: 'properties', file: 'server.properties', key: 'online-mode' },
    },
    {
      key: 'pvp',
      type: 'boolean',
      label: 'Players can damage each other',
      help: 'Turn off for a purely cooperative server.',
      tier: 'basic',
      group: 'Basics',
      default: true,
      target: { kind: 'properties', file: 'server.properties', key: 'pvp' },
    },

    // ── World ───────────────────────────────────────────────────────────
    {
      key: 'level-name',
      type: 'string',
      label: 'World folder',
      help: 'The folder your world is saved in. Changing this creates a brand new world and leaves the old one untouched on disk.',
      tier: 'advanced',
      group: 'World',
      default: 'world',
      maxLength: 64,
      pattern: '^[A-Za-z0-9._-]+$',
      restartRequired: true,
      target: { kind: 'properties', file: 'server.properties', key: 'level-name' },
    },
    {
      key: 'level-seed',
      type: 'string',
      label: 'World seed',
      help: 'Leave empty for a random world. Paste a seed to generate a specific one. Only used the first time the world is created.',
      tier: 'basic',
      group: 'World',
      default: '',
      maxLength: 64,
      placeholder: 'random',
      restartRequired: true,
      target: { kind: 'properties', file: 'server.properties', key: 'level-seed' },
    },
    {
      key: 'level-type',
      type: 'enum',
      label: 'World type',
      help: 'The shape of the generated world.',
      tier: 'advanced',
      group: 'World',
      default: 'minecraft:normal',
      options: [
        { value: 'minecraft:normal', label: 'Normal' },
        { value: 'minecraft:flat', label: 'Superflat', help: 'A flat world, useful for building and testing.' },
        { value: 'minecraft:large_biomes', label: 'Large biomes' },
        { value: 'minecraft:amplified', label: 'Amplified', help: 'Extreme terrain. Demanding on the server.' },
      ],
      restartRequired: true,
      target: { kind: 'properties', file: 'server.properties', key: 'level-type' },
    },
    {
      key: 'hardcore',
      type: 'boolean',
      label: 'Hardcore',
      help: 'Death is permanent — players are switched to spectator when they die.',
      tier: 'advanced',
      group: 'World',
      default: false,
      target: { kind: 'properties', file: 'server.properties', key: 'hardcore' },
    },
    {
      key: 'allow-nether',
      type: 'boolean',
      label: 'Allow the Nether',
      help: 'Turning this off disables Nether portals entirely.',
      tier: 'advanced',
      group: 'World',
      default: true,
      target: { kind: 'properties', file: 'server.properties', key: 'allow-nether' },
    },
    {
      key: 'spawn-protection',
      type: 'number',
      label: 'Spawn protection radius',
      help: 'Blocks around spawn that only operators can build in. Set to 0 to let anyone build anywhere.',
      tier: 'advanced',
      group: 'World',
      default: 16,
      min: 0,
      max: 512,
      unit: 'blocks',
      target: { kind: 'properties', file: 'server.properties', key: 'spawn-protection' },
    },

    // ── Performance ─────────────────────────────────────────────────────
    {
      key: 'view-distance',
      type: 'number',
      label: 'View distance',
      help: 'How far players can see, in chunks. This is the biggest single lever on server performance — 8 is comfortable, 16 is expensive.',
      tier: 'basic',
      group: 'Performance',
      default: 10,
      min: 3,
      max: 32,
      unit: 'chunks',
      target: { kind: 'properties', file: 'server.properties', key: 'view-distance' },
    },
    {
      key: 'simulation-distance',
      type: 'number',
      label: 'Simulation distance',
      help: 'How far from a player the world keeps ticking — mobs moving, crops growing. Lower it before lowering view distance.',
      tier: 'advanced',
      group: 'Performance',
      default: 10,
      min: 3,
      max: 32,
      unit: 'chunks',
      target: { kind: 'properties', file: 'server.properties', key: 'simulation-distance' },
    },
    {
      key: 'max-tick-time',
      type: 'number',
      label: 'Watchdog timeout',
      help: 'The server shuts itself down if a single tick takes longer than this, assuming it has hung. Set to -1 to disable, which is common on heavily modded servers.',
      tier: 'expert',
      group: 'Performance',
      default: 60000,
      min: -1,
      max: 600000,
      unit: 'ms',
      target: { kind: 'properties', file: 'server.properties', key: 'max-tick-time' },
    },
    {
      key: 'sync-chunk-writes',
      type: 'boolean',
      label: 'Synchronous chunk writes',
      help: 'Safer against power loss, slower on spinning disks. Most hosts leave this off.',
      tier: 'expert',
      group: 'Performance',
      default: false,
      target: { kind: 'properties', file: 'server.properties', key: 'sync-chunk-writes' },
    },

    // ── Access ──────────────────────────────────────────────────────────
    {
      key: 'white-list',
      type: 'boolean',
      label: 'Allowlist only',
      help: 'Only players you have added can join. The strongest protection against uninvited guests.',
      tier: 'basic',
      group: 'Access',
      default: false,
      target: { kind: 'properties', file: 'server.properties', key: 'white-list' },
    },
    {
      key: 'enforce-whitelist',
      type: 'boolean',
      label: 'Kick players removed from the allowlist',
      help: 'Disconnects players immediately when they are taken off the allowlist, instead of at their next join.',
      tier: 'advanced',
      group: 'Access',
      default: true,
      showWhen: { key: 'white-list', equals: [true] },
      target: { kind: 'properties', file: 'server.properties', key: 'enforce-whitelist' },
    },
    {
      key: 'enable-command-block',
      type: 'boolean',
      label: 'Enable command blocks',
      help: 'Needed by many adventure maps and datapacks.',
      tier: 'advanced',
      group: 'Access',
      default: false,
      target: { kind: 'properties', file: 'server.properties', key: 'enable-command-block' },
    },
    {
      key: 'enable-rcon',
      type: 'boolean',
      label: 'Enable remote console (RCON)',
      help: 'Lets external tools send console commands, and makes the panel console show what a command replied instead of only what the server logs. Not required — without it the panel still sends commands, it just cannot read the answer. Set a password below.',
      tier: 'expert',
      group: 'Access',
      default: false,
      restartRequired: true,
      target: { kind: 'properties', file: 'server.properties', key: 'enable-rcon' },
    },
    {
      key: 'rcon.password',
      type: 'string',
      label: 'RCON password',
      help: 'Required when remote console is on. Use a long random value.',
      tier: 'expert',
      group: 'Access',
      default: '',
      secret: true,
      maxLength: 128,
      showWhen: { key: 'enable-rcon', equals: [true] },
      target: { kind: 'properties', file: 'server.properties', key: 'rcon.password' },
    },
  ];

  // The modpack variants need to know which pack to install. These are
  // `internal` targets — they drive the installer, not a config file — and
  // the deploy wizard renders them as the very first question.
  if (variantId === 'modrinth-modpack') {
    schema.unshift(
      {
        key: 'modpack_project',
        type: 'string',
        label: 'Modrinth modpack',
        help: 'Paste the modpack link or its short name, e.g. "cobblemon-fabric". You can find it in the address bar on modrinth.com.',
        tier: 'basic',
        group: 'Modpack',
        default: '',
        minLength: 1,
        maxLength: 300,
        placeholder: 'https://modrinth.com/modpack/…',
        restartRequired: true,
        target: { kind: 'internal' },
      },
      {
        key: 'modpack_version',
        type: 'string',
        label: 'Pack version',
        help: 'Leave empty to install the newest release the pack offers.',
        tier: 'advanced',
        group: 'Modpack',
        default: '',
        maxLength: 64,
        placeholder: 'latest',
        restartRequired: true,
        target: { kind: 'internal' },
      },
    );
  }

  if (variantId === 'custom-modpack') {
    schema.unshift(
      {
        key: 'modpack_zip_url',
        type: 'string',
        label: 'Server pack URL',
        help: 'Direct download link to the server pack .zip, if you have one. Otherwise upload the file in the wizard.',
        tier: 'basic',
        group: 'Modpack',
        default: '',
        maxLength: 2048,
        placeholder: 'https://…/server-pack.zip',
        restartRequired: true,
        target: { kind: 'internal' },
      },
      {
        key: 'modpack_staging_id',
        type: 'string',
        label: 'Uploaded pack',
        help: 'Filled automatically when you upload a .zip in the deploy wizard.',
        tier: 'expert',
        group: 'Modpack',
        default: '',
        maxLength: 64,
        restartRequired: true,
        target: { kind: 'internal' },
      },
    );
  }

  // Plugin platforms expose a Bukkit-family knob that Vanilla/Fabric lack.
  if (variantId === 'paper' || variantId === 'purpur') {
    schema.push({
      key: 'sf_paper_flare',
      type: 'boolean',
      label: 'Accept transfers from other servers',
      help: 'Allows players to be sent here from another server in a network. Leave off for a standalone server.',
      tier: 'expert',
      group: 'Access',
      default: false,
      restartRequired: true,
      target: { kind: 'properties', file: 'server.properties', key: 'accepts-transfers' },
    });
  }

  return schema;
}
