import type { SettingsSchema } from '@serverforge/core';

export const bedrockSettings = (
  [
    {
      key: 'server-name',
      type: 'string',
      label: 'Server message',
      help: 'The name shown in the Bedrock server list.',
      tier: 'basic',
      group: 'Basics',
      default: 'A ServerForge server',
      maxLength: 120,
      pattern: '^[^;\\\\\\r\\n]+$',
      target: { kind: 'properties', file: 'server.properties', key: 'server-name' },
    },
    {
      key: 'max-players',
      type: 'number',
      label: 'Max players',
      help: 'How many people can play at once. More players need more memory and CPU.',
      tier: 'basic',
      group: 'Basics',
      default: 10,
      min: 1,
      max: 1000,
      unit: 'players',
      target: { kind: 'properties', file: 'server.properties', key: 'max-players' },
    },
    {
      key: 'gamemode',
      type: 'enum',
      label: 'Game mode',
      help: 'The starting game mode for new players.',
      tier: 'basic',
      group: 'Basics',
      default: 'survival',
      options: [
        { value: 'survival', label: 'Survival' },
        { value: 'creative', label: 'Creative' },
        { value: 'adventure', label: 'Adventure' },
      ],
      target: { kind: 'properties', file: 'server.properties', key: 'gamemode' },
    },
    {
      key: 'difficulty',
      type: 'enum',
      label: 'Difficulty',
      help: 'How dangerous monsters are. Peaceful removes hostile monsters.',
      tier: 'basic',
      group: 'Basics',
      default: 'normal',
      options: [
        { value: 'peaceful', label: 'Peaceful' },
        { value: 'easy', label: 'Easy' },
        { value: 'normal', label: 'Normal' },
        { value: 'hard', label: 'Hard' },
      ],
      target: { kind: 'properties', file: 'server.properties', key: 'difficulty' },
    },
    {
      key: 'allow-list',
      type: 'boolean',
      label: 'Invite-only game',
      help: 'Only players in allowlist.json can join. Add gamertags with allowlist add in the console; dashboard invitations are separate.',
      tier: 'basic',
      group: 'Access',
      default: true,
      target: { kind: 'properties', file: 'server.properties', key: 'allow-list' },
    },
    {
      key: 'online-mode',
      type: 'boolean',
      label: 'Verify Microsoft accounts',
      help: 'Keep enabled for public servers. Remote players must authenticate even if this is disabled.',
      tier: 'advanced',
      group: 'Access',
      default: true,
      target: { kind: 'properties', file: 'server.properties', key: 'online-mode' },
    },
    {
      key: 'allow-cheats',
      type: 'boolean',
      label: 'Allow cheats',
      help: 'Enables gameplay commands such as changing time and teleporting. Enabling cheats disables achievements for the world.',
      tier: 'basic',
      group: 'World',
      default: false,
      target: { kind: 'properties', file: 'server.properties', key: 'allow-cheats' },
    },
    {
      key: 'level-name',
      type: 'string',
      label: 'World folder',
      help: 'Saved under worlds/. Changing this selects or creates another world; it does not convert a Java world.',
      tier: 'advanced',
      group: 'World',
      default: 'Bedrock level',
      minLength: 1,
      maxLength: 64,
      pattern: '^[A-Za-z0-9](?:[A-Za-z0-9 _.-]*[A-Za-z0-9_-])?$',
      target: { kind: 'properties', file: 'server.properties', key: 'level-name' },
    },
    {
      key: 'level-seed',
      type: 'string',
      label: 'World seed',
      help: 'Leave empty for a random world. Used only when creating a new world.',
      tier: 'basic',
      group: 'World',
      default: '',
      maxLength: 64,
      pattern: '^[^\\\\\\r\\n]*$',
      target: { kind: 'properties', file: 'server.properties', key: 'level-seed' },
    },
    {
      key: 'force-gamemode',
      type: 'boolean',
      label: 'Apply game mode on every join',
      help: 'Use the configured game mode instead of the mode saved for each player.',
      tier: 'advanced',
      group: 'World',
      default: false,
      target: { kind: 'properties', file: 'server.properties', key: 'force-gamemode' },
    },
    {
      key: 'view-distance',
      type: 'number',
      label: 'View distance',
      help: 'How far players can see. Lower this to reduce memory and network usage.',
      tier: 'advanced',
      group: 'Performance',
      default: 16,
      min: 5,
      max: 96,
      unit: 'chunks',
      target: { kind: 'properties', file: 'server.properties', key: 'view-distance' },
    },
    {
      key: 'tick-distance',
      type: 'number',
      label: 'Simulation distance',
      help: 'How far around each player the world runs. Lower this to reduce CPU usage.',
      tier: 'advanced',
      group: 'Performance',
      default: 4,
      min: 4,
      max: 12,
      unit: 'chunks',
      target: { kind: 'properties', file: 'server.properties', key: 'tick-distance' },
    },
    {
      key: 'player-idle-timeout',
      type: 'number',
      label: 'Idle player timeout',
      help: 'Disconnect inactive players after this long. Set to 0 to let them stay.',
      tier: 'advanced',
      group: 'Access',
      default: 30,
      min: 0,
      max: 1440,
      unit: 'minutes',
      target: { kind: 'properties', file: 'server.properties', key: 'player-idle-timeout' },
    },
    {
      key: 'default-player-permission-level',
      type: 'enum',
      label: 'New player permissions',
      help: 'Members can play normally. Visitors can look around. Operators can administer the game.',
      tier: 'advanced',
      group: 'Access',
      default: 'member',
      options: [
        { value: 'visitor', label: 'Visitor' },
        { value: 'member', label: 'Member' },
        { value: 'operator', label: 'Operator' },
      ],
      target: {
        kind: 'properties',
        file: 'server.properties',
        key: 'default-player-permission-level',
      },
    },
    {
      key: 'texturepack-required',
      type: 'boolean',
      label: 'Require world resource packs',
      help: 'Players must accept the resource packs attached to this Bedrock world to join.',
      tier: 'advanced',
      group: 'Add-ons',
      default: false,
      target: { kind: 'properties', file: 'server.properties', key: 'texturepack-required' },
    },
  ] satisfies SettingsSchema
).map((setting) => ({ ...setting, restartRequired: true }));
